import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert(
      'food_ingredients',
      [
        {
          food_id: 1,
          ing_id: 1,
          unity: 'und',
          quantity: 1,
          is_additional: false,
        },
        {
          food_id: 1,
          ing_id: 3,
          unity: 'und',
          quantity: 1,
          is_additional: false,
        },
        {
          food_id: 1,
          ing_id: 5,
          unity: 'gr',
          quantity: 4,
          is_additional: false,
        },
        {
          food_id: 1,
          ing_id: 6,
          unity: 'gr',
          quantity: 4,
          is_additional: false,
        },
        {
          food_id: 1,
          ing_id: 7,
          unity: 'gr',
          quantity: 5,
          is_additional: false,
        },
        {
          food_id: 1,
          ing_id: 9,
          unity: 'gr',
          quantity: 5,
          is_additional: false,
        },
        {
          food_id: 1,
          ing_id: 3,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 4.00,
        },
        {
          food_id: 1,
          ing_id: 15,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 4.00,
        },
        {
          food_id: 1,
          ing_id: 10,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 4.00,
        },
        {
          food_id: 1,
          ing_id: 11,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 2.50,
        },
        {
          food_id: 1,
          ing_id: 19,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 4.50,
        },
        {
          food_id: 1,
          ing_id: 13,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 4.50,
        },
        {
          food_id: 1,
          ing_id: 27,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 3.50,
        },
        {
          food_id: 1,
          ing_id: 28,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 3.50,
        },
        {
          food_id: 1,
          ing_id: 29,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 3.50,
        },
        {
          food_id: 2,
          ing_id: 1,
          unity: 'und',
          quantity: 1,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 3,
          unity: 'und',
          quantity: 1,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 21,
          unity: 'und',
          quantity: 1,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 5,
          unity: 'gr',
          quantity: 2,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 6,
          unity: 'und',
          quantity: 4,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 7,
          unity: 'gr',
          quantity: 5,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 9,
          unity: 'gr',
          quantity: 1,
          is_additional: false,
        },
        {
          food_id: 2,
          ing_id: 3,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 4.00,
        },
        {
          food_id: 2,
          ing_id: 15,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 4.00,
        },
        {
          food_id: 2,
          ing_id: 10,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 4.00,
        },
        {
          food_id: 2,
          ing_id: 11,
          unity: 'und',
          quantity: 2,
          is_additional: true,
          plus_price: 2.50,
        },
        {
          food_id: 2,
          ing_id: 19,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 4.50,
        },
        {
          food_id: 2,
          ing_id: 13,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 4.50,
        },
        {
          food_id: 2,
          ing_id: 27,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 3.50,
        },
        {
          food_id: 2,
          ing_id: 28,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 3.50,
        },
        {
          food_id: 2,
          ing_id: 29,
          unity: 'und',
          quantity: 1,
          is_additional: true,
          plus_price: 3.50,
        },
      ],
      {},
    );
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete('food_ingredients', {});
  },
}